# Generated by Django 2.1 on 2021-05-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attrition_upload',
            fields=[
                ('tables_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='example', max_length=30)),
                ('file_name', models.CharField(max_length=100)),
                ('date_of_upload', models.DateField(auto_now_add=True)),
                ('file_upload', models.FileField(upload_to='HR')),
            ],
        ),
        migrations.CreateModel(
            name='sentiment',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentiment1', models.CharField(blank=True, default='not filled', max_length=500, null=True)),
                ('sentiment2', models.CharField(blank=True, default='not filled', max_length=500, null=True)),
                ('sentiment3', models.CharField(blank=True, default='not filled', max_length=500, null=True)),
                ('sentiment4', models.CharField(blank=True, default='not filled', max_length=500, null=True)),
                ('sentiment5', models.CharField(blank=True, default='not filled', max_length=500, null=True)),
            ],
        ),
    ]
